import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";
import { randomUUID } from "crypto";
import nodemailer from "nodemailer";
import QRCode from "qrcode";
import { PDFDocument, rgb } from "pdf-lib";

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  try {
    const authRole = req.cookies.get("auth_role")?.value;
    if (authRole !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
    }

    const { name, email, role = "Participant", sendEmail = true } = await req.json();

    if (!name || !email) {
      return NextResponse.json({ error: "Name and email required" }, { status: 400 });
    }

    const token = randomUUID();

    // 1. Insert into Supabase (meal_usages are generated by DB trigger as per schema)
    const { data: participant, error: insertError } = await supabase
      .from("participants")
      .insert({ name, email, token, role })
      .select()
      .single();

    if (insertError) {
      return NextResponse.json({ error: insertError.message }, { status: 500 });
    }

    if (sendEmail) {
      // 2. Generate QR Code and PDF
      const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
      const qrDataUrl = await QRCode.toDataURL(`${appUrl}/scan?token=${token}`, { margin: 1 });
      
      // Create PDF
      const pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([400, 500]);
      const qrImageResponse = await fetch(qrDataUrl);
      const qrImageArrayBuffer = await qrImageResponse.arrayBuffer();
      const qrImage = await pdfDoc.embedPng(qrImageArrayBuffer);
      
      page.drawText(`Hello ${name},`, { x: 50, y: 450, size: 24, color: rgb(0, 0, 0) });
      page.drawText(`Role: ${role}`, { x: 50, y: 410, size: 18, color: rgb(0.3, 0.3, 0.3) });
      page.drawText(`Present this code at the event scanners:`, { x: 50, y: 380, size: 14, color: rgb(0, 0, 0) });
      page.drawImage(qrImage, { x: 50, y: 50, width: 300, height: 300 });
      
      const pdfBytes = await pdfDoc.save();
      const pdfBuffer = Buffer.from(pdfBytes);

      // 3. Send Email using Nodemailer
      const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST || "smtp.ethereal.email",
        port: Number(process.env.SMTP_PORT) || 587,
        auth: {
          user: process.env.SMTP_USER || "dummy_user",
          pass: process.env.SMTP_PASS || "dummy_pass",
        },
      });

      try {
        await transporter.sendMail({
          from: '"Team CRPLPJ" <no-reply@event.com>',
          to: email,
          subject: "Event QR Coupon for lunch",
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; line-height: 1.6;">
              <p>Hello, ${name}!</p>
              <p>We are delighted to share your official QR Coupon for lunch.</p>
              <p>Please find your personalized PDF pass attached to this email. You will need to present it at the scanning desk to verify your attendance and meal allocation.</p>
              <p><strong>Role:</strong> ${role}</p>
              <p style="margin-bottom: 30px;">If you experience any difficulties opening the attachment, your manual reference token is: <strong>${token}</strong></p>
              
              <p style="border-top: 1px solid #e5e7eb; padding-top: 20px;">
                <em><strong>Thanks and Regards, <br/>
                Centre for Research in Public Law, Policy and Jurisprudence <br/>
                Maharashtra National Law University Mumbai.</strong></em>
              </p>
            </div>
          `,
          attachments: [
            {
              filename: 'Event_QR_Pass.pdf',
              content: pdfBuffer,
              contentType: 'application/pdf',
            }
          ]
        });
      } catch (emailError: any) {
        console.warn("Email failed to send, but participant was created", emailError);
        // Not returning 500 here since DB creation succeeded
      }
    }

    return NextResponse.json({ success: true, participant });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function GET() {
  try {
    let { data: participants, error } = await supabase
      .from("participants")
      .select(`
        id, name, email, role, token, created_at,
        meal_usage(meal_type, is_used, used_at),
        scan_logs(id, meal_type, status)
      `)
      .order("created_at", { ascending: false });

    if (error) throw error;

    if (participants && !participants.some(p => p.token === 'MASTER_QR_UNLIMITED')) {
      const { data: newMaster } = await supabase.from("participants").insert({
        name: 'Master Key',
        email: 'master@admin.key',
        token: 'MASTER_QR_UNLIMITED',
        role: 'Admin Master'
      }).select(`
        id, name, email, role, token, created_at,
        meal_usage(meal_type, is_used, used_at),
        scan_logs(id, meal_type, status)
      `).single();
      
      if (newMaster) participants = [newMaster, ...participants];
    }

    return NextResponse.json(participants);
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
